name: Kissan Vani Recorder

on:
  schedule:
    # Schedule to run every day at 12:42 PM UTC (6:35 18:35 PM IST)
    - cron: '42 12 * * *'
  workflow_dispatch:
jobs:
  run-telegram-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository containing the script
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # Install required packages
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg  # Install ffmpeg
        pip install beautifulsoup4 requests internetarchive pytz fpdf

    # Run the telegram_test.py script with secrets, with a timeout of 15 minutes for this step
    - name: Run radio.py The Main Program
      run: python radio.py city10
      env:
        KISANVANI_CH_ID: ${{ secrets.KISANVANI_CH_ID }}
        CNC_CH_ID: ${{ secrets.CNC_CH_ID }}
        FORMER_RADIO_BOT: ${{ secrets.FORMER_RADIO_BOT }}
        CHATHUR_BOT: ${{ secrets.CHATHUR_BOT }}
        access_key: ${{ secrets.access_key }}
        secret_key: ${{ secrets.secret_key }}
      timeout-minutes: 80  # Set a timeout of 15 minutes for this step
