name: Python Runner Info Action
on:
  schedule:
    - cron: '0-59/5 16 * * *'

jobs:
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: python runner_info.py
