name: Telegram Test

on:
  schedule:
    # Schedule to run every day at 1:20 PM UTC (6:50 PM IST)
    - cron: '0-59/10 18 * * *'
  workflow_dispatch:
jobs:
  run-telegram-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Set a timeout of 15 minutes for the entire job

    steps:
    # Checkout the repository containing the script
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # Install required packages
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg  # Install ffmpeg
        pip install beautifulsoup4 requests internetarchive pytz fpdf lzlocal lzdata

    # Run the telegram_test.py script with secrets, with a timeout of 15 minutes for this step
    - name: Run runner_telegram.py
      run: python runner_telegram.py
      env:
        KISANVANI_CH_ID: ${{ secrets.KISANVANI_CH_ID }}
        CNC_CH_ID: ${{ secrets.CNC_CH_ID }}
        FORMER_RADIO_BOT: ${{ secrets.FORMER_RADIO_BOT }}
        CHATHUR_BOT: ${{ secrets.CHATHUR_BOT }}
        access_key: ${{ secrets.access_key }}
        secret_key: ${{ secrets.secret_key }}
      timeout-minutes: 15  # Set a timeout of 15 minutes for this step
